In [24]:
import numpy as np
import pandas as pd
import plotly.express as px
import matplotlib.pyplot as plt
from scipy.ndimage import rotate
from sklearn.model_selection import train_test_split
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import LinearRegression
from sklearn.metrics import classification_report, confusion_matrix
import torchvision

In [ ]:
# import the dataset

dataset = torchvision.datasets.FashionMNIST(root="./data", train=True, download=True)
images = dataset.data.numpy().reshape(-1, 784).astype(float)
labels = np.array([dataset.classes[t] for t in dataset.targets.numpy()])

df = pd.DataFrame({"label": labels})
df['image'] = list(images)

In [ ]:
# check repartition
df["label"].value_counts()

label
Ankle boot     6000
T-shirt/top    6000
Dress          6000
Pullover       6000
Sneaker        6000
Sandal         6000
Trouser        6000
Shirt          6000
Coat           6000
Bag            6000
Name: count, dtype: int64

In [48]:
#dataset is balanced, lets split the data
X_train,X_test, y_train, y_test = train_test_split(df["image"],df["label"],test_size = 0.2)
df_train = pd.DataFrame({"image":X_train,"label":y_train})

In [49]:
df_train

                                                   image        label
38435  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   Ankle boot
38481  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...      Sneaker
24189  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...       Sandal
32394  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, ...         Coat
30983  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...      Sneaker
...                                                  ...          ...
11826  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, ...        Dress
21286  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  T-shirt/top
44442  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...       Sandal
17811  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...       Sandal
25926  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...        Dress

[48000 rows x 2 columns]

In [50]:
#train Kmeans
classifier = KMeans(n_clusters = 10)
predictions = classifier.fit_predict(np.stack(X_train.values),y_train.values)
predictions

array([5, 6, 1, ..., 1, 6, 0], shape=(48000,), dtype=int32)

In [60]:
#add the cluster to the df
df_train["cluster"] = predictions

In [80]:
repartition_cluster = df_train.groupby("label")["cluster"].value_counts().reset_index()

In [81]:
repartition_cluster

         label  cluster  count
0   Ankle boot        5   2303
1   Ankle boot        8   2244
2   Ankle boot        1    112
3   Ankle boot        6     90
4   Ankle boot        3     15
..         ...      ...    ...
73     Trouser        1    229
74     Trouser        4     51
75     Trouser        3     33
76     Trouser        7     12
77     Trouser        2      4

[78 rows x 3 columns]

In [90]:

pd.options.plotting.backend = "plotly"
repartition_cluster.plot.bar(x = "cluster",y="count",color = "label")